<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>AiStructuredDataFromImageExtractionDemo</RootNamespace>
		<UserSecretsId>16a3140d-80aa-46d6-a730-256a95d896d9</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Azure.AI.DocumentIntelligence" Version="1.0.0" />
		<PackageReference Include="Azure.AI.OpenAI" Version="2.1.0" />
		<PackageReference Include="Microsoft.Extensions.AI" Version="10.3.0" />
		<PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.3.0" />
		<PackageReference Include="Havit.Blazor.Components.Web.Bootstrap" Version="4.24.0" />
		<PackageReference Include="Markdig" Version="0.38.0" />
	</ItemGroup>

</Project>
